lower_toUpper: lower_toUpper.o main.o
	gcc -g lower_toUpper.o main.o -o lower_toUpper

lower_toUpper.o: lower_toUpper.c
	gcc -g -c lower_toUpper.c -o lower_toUpper.o

main.o: main.c
	gcc -g -c main.c -o main.o
