
Contar_Palavras: count_words.o main.o
	gcc count_words.o main.o -o Contar_Palavras

count_words.o: count_words.c
	gcc -Wall -c count_words.c -o count_words.o

main.o: main.c
	gcc -Wall -c main.c -o main.o
